version: "3"
services:
  bot:
    build: .
    restart: always
    volumes:
      - ./app:/app
    environment:
      API_TOKEN: "API_TOKEN"
      TG_API_URL: "http://telegram-bot-api:8081"
    depends_on:
      - telegram-bot-api

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "TELEGRAM_API_ID"
      TELEGRAM_API_HASH: "TELEGRAM_API_HASH"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    expose:
      - "8081"

volumes:
  telegram-bot-api-data:
